[package]
name = 'benstrobel/media-provider-plugin-contracts'
version = '0.1.0'
description = 'Description for package plugin-contracts-app'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'benstrobel/media-provider-plugin-contracts'
source = './target/wasm32-wasip2/debug/plugin_media_provider_fs.wasm'
abi = 'wasi'
